Algoritmo "maior que ou menor que"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Conversão de fahrenheit para celsius
// Autor(a)    : Bruno Silva
// Data atual  : 23/03/2022
Var
numero:inteiro
Inicio
Escreval("Digite um número:")
leia(numero)
se (numero >= 10) entao
   Escreval("Número maior que 10")
senao
   Escreval("Número menor que 10")
fimse



Fimalgoritmo