Algoritmo "multiplica"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/03/2022
Var
num1:inteiro
num2:inteiro
soma:inteiro
Inicio
Escreva("Digite um número: ")
Leia(num1)
Escreva("Digite mais um número: ")
Leia(num2)
soma<-num1*num2
Escreva("O valor total da soma é de: ", soma)

Fimalgoritmo