Algoritmo "par ou impar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   :
// Autor(a)    : Bruno Silva
// Data atual  : 25/03/2022
Var
numero1:inteiro


Inicio
Escreval("Digite um número")
leia(numero1)

se (numero1 % 2 = 0) entao
   Escreval(numero1, " é um número par")
senao
     Escreval(numero1, " é num número impar")
fimse





Fimalgoritmo