Algoritmo "positivo ou negativo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Conversão de fahrenheit para celsius
// Autor(a)    : Bruno Silva
// Data atual  : 23/03/2022
Var
numero:inteiro
Inicio
Escreval("Digite um número:")
leia(numero)
se (numero >= 0) entao
   Escreval("Número positivo")
senao
   Escreval("Número negativo")
fimse



Fimalgoritmo