Algoritmo "atividade2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Area de um retângulo
// Autor(a)    : Bruno Martins de Morais Silva
// Data atual  : 02/06/2022
Var
   base:inteiro
   altura:inteiro
   area:inteiro

Inicio
   Escreval("Digite o valor da base: ")
   leia(base)
   Escreval("Digite o valor da altura: ")
   leia(altura)
   area <- base * altura
   Escreval(area)


Fimalgoritmo