Algoritmo "media1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Conversão de fahrenheit para celsius
// Autor(a)    : Bruno Silva
// Data atual  : 23/03/2022
Var
n1:inteiro
n2:inteiro
n3:inteiro
media:real


Inicio
Escreval("Digite a primeira nota:")
leia(n1)
Escreval("Digite a segunda nota:")
leia(n2)
Escreval("Digite a terceira nota:")
leia(n3)
media<- (n1 * 2 + n2 * 3 + n3 * 5) / 10
Escreval("A média é de: ", media)