Algoritmo "Conversão fahrenheit em celsius"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Conversão de fahrenheit para celsius
// Autor(a)    : Bruno Silva
// Data atual  : 23/03/2022
Var
valor:real
f:real
c:real
convert:real


Inicio
Escreval("Digite os graus em fahrenheit:")
leia(valor)
f<- (valor - 32)
c<- f * (5 / 9)
Escreval("Em Celsius este valor é igual á: ", c)
Fimalgoritmo