Algoritmo "Conversão celsius em fahrenheit"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Conversão de fahrenheit para celsius
// Autor(a)    : Bruno Silva
// Data atual  : 23/03/2022
Var
valor:real
f:real
c:real
convert:real


Inicio
Escreval("Digite os graus em celsius:")
leia(valor)
c<- (valor * 9 /5)
f<- (c + 32)
Escreval("Em fahrenheit este valor é igual á: ", f)
Fimalgoritmo